### PR TITLE
Configure Camunda client scopes

### PR DESCRIPTION
**Pull request by multani**
This introduces a new "scopes" attribute on Camunda cluster client resource to configure the scopes/permissions for the client.

Note that at the moment, setting `scopes = []` creates a client with all the scopes. It seems to be an issue coming from the Go client and/or the API itself.

Closes: https://github.com/camunda-community-hub/terraform-provider-camunda/issues/80

### CODE REVIEW

**Review by Sijoma — APPROVED** [review]
Looks good. 

Should we handle the empty scope array for now as a terraform validation? I get that you can create a empty client on Console and with the API. However, I'm not sure it makes sense actually. Probably its good to put it in an issue.

LGTM! 🚀

**Comment by multani** [comment]
@Sijoma I required at least one scope to be specified, that should cover the case "empty list of scopes == all scopes".

I'll check whether this bug comes from the Go client and/or from the API, I would really prefer the provider maps what the API provides instead of reinventing constraints.

Also, the issue in the Go client where "empty list == no list" will probably bite us somewhere at some point, if the API exposes list attributes somewhere (looking at you, IP whitelisting)

**Comment by Sijoma** [comment]
> @Sijoma I required at least one scope to be specified, that should cover the case "empty list of scopes == all scopes".
> 
> I'll check whether this bug comes from the Go client and/or from the API, I would really prefer the provider maps what the API provides instead of reinventing constraints.
> 
> Also, the issue in the Go client where "empty list == no list" will probably bite us somewhere at some point, if the API exposes list attributes somewhere (looking at you, IP whitelisting)

Feel free to also us a ticket on the generated client. I'm also interested to take a look if there are some settings that we can tweak or if we have to tweak it in the spec.

**Comment by multani** [comment]
@Sijoma I created an issue to see if the API can be adjusted / made more clear, I'll take a look at the Go client afterwards.

**Pull request merged**
